services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    build:
      context: requirements/nginx/.
      dockerfile: Dockerfile
    ports:
      - 443:443
    mariadb:
      restart: always
      image: mariadb
      container_name: mariadb
      build:
        context: requirements/nginx/.
        dockerfile: Dockerfile
        