services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    build:
      context: requirements/nginx/.
      dockerfile: Dockerfile
    ports:
      - 443:443
  mariadb:
    restart: always
    image: mariadb
    container_name: mariadb
    build:
      context: requirements/mariadb/.
      dockerfile: Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
  wordpress:
    depends_on:
      - mariadb
    restart: always
    image: wordpress
    container_name: wordpress
    build:
      context: requirements/wordpress/.
      dockerfile: Dockerfile
  network:
    my_network:
      name: my_network
        