services:
  nginx:
    depends_on:
      - wordpress
    restart: always
    init: true
    image: nginx
    container_name: nginx
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - 443:443
    networks:
      - inceptionNet
    volumes:
      - wordpress:/var/www/html/
  mariadb:
    restart: always
    image: mariadb
    container_name: mariadb
    init: true
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
    volumes:
      - db:/var/lib/mysql/
    networks: 
      - inceptionNet
  wordpress:
    depends_on:
      - mariadb
    restart: always
    image: wordpress
    container_name: wordpress
    init: true
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    environment:
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_ADMIN_MAIL: ${WP_ADMIN_MAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASS: ${WP_USER_PASS}
      WP_USER_MAIL: ${WP_USER_MAIL}
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inceptionNet
volumes:
  db:
    name: db
    driver: local
    # driver_opts:
    #   device: /Users/kdelport/db
    #   o: bind
    #   type: none
  wordpress:
    name: wordpress
    driver: local
    # driver_opts:
    #   device: /Users/kdelport/wp
    #   o: bind
    #   type: none 
networks:
    inceptionNet:
      name: inceptionNet
      driver: bridge

        